name: Android CI

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build On Merge
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Make gradlew Executable
        run: chmod +x ./gradlew
      - name: Run Android Lint
        run: ./gradlew lintDebug
      - name: Run Unit Test
        run: ./gradlew testDebug
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
